### ISSUE TITLE
Foundry 11 testing/Bugs

### ISSUE THREAD

**Issue by TheGam1ngWizard** [SobranDM/foundryvtt-wwn#67]
Hi there! 

I'm just going to use this to log down issues with v11 beta.

So far, everything mostly works when it comes to players and rolling - Oddly enough though
_Converted monster sheets cannot be opened_
This applies to both ones previously made by me (in a prior version) and _all monsters_ from the compendium.

**Comment by Theduckthatsits** [comment]
I've found two errors, one with the skills where if you try and edit the skill, this commonly happens with is Magic, it provides you with the error item does not exist. Attached is an image of the error. 
![image](https://github.com/SobranDM/foundryvtt-wwn/assets/35312716/eb660a4f-af7d-48d2-a566-e5fc04804364)


The second one is related to unlinked tokens, you cannot update any of their stats and particularly importantly the random HP is broken because of that. The error says the actor is not a valid embedded document within the token document. 
![image](https://github.com/SobranDM/foundryvtt-wwn/assets/35312716/db1dcdb7-9c85-4046-aef8-1c7ce84bd5f2)

**Comment by SobranDM** [comment]
Unfortunately, WWN is not yet ready for Foundry v11.

**Comment by Theduckthatsits** [comment]
I though the post was asking for bugs with the existing version of WWN with foundry v11 so that they can more easily be identified and be corrected. Anyways I noticed WWN was out of date and not exactly compatible after I was about halfway to preparing my campaign and didn't want to re-type everything. When I tried rolling back foundry the data didn't follow so I'm stuck with the slightly buggy version for now. Figured I'd document what isn't working so it's easier to to fix what isn't compatible with v11. 

I did run into another issue. Character sheets when provided to a player as the owner will lose half their skills from the list as they start editing it. This always happens just as they start editing it. Creating and assigning them a new character sheet after that fixes the issue. Then I usually have to duplicate the sheet thanks to the first error i mentioned in the post above but afterwards it works normally.

**Comment by Theduckthatsits** [comment]
Glad to hear it's nearly done. Thanks for all the work you've put into this. 
I've got another one for you, the weapons in the compendium when dragged into the character sheet default to having magic as the skill used for them and while magic is the skill for the weapon, you cannot start the roll macro.

**Comment by SobranDM** [comment]
Should all be fixed. Any lingering v11 bugs should open new issues.
